# Whoami                                                                       #
# Copyright (c) 2017 Jeron Lau (Plop Grizzly) <jeron.lau@plopgrizzly.com>      #
# Licensed under the MIT LICENSE                                               #
#                             _        _                                       #
#                            /@\——————/@\                                      #
# .———  .                   |   o    o   |     .————      .            .       #
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   . #
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   | #
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /  #
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |   #
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |   #
#                 |        \              /                              __/   #
#                           ¯————————————¯                                     #
# Cargo.toml                                                                   #

################################################################################

[package]
name = "whoami"
version = "0.2.0"
authors = ["Jeron Aldaron Lau (Plop Grizzly) <jeron.lau@plopgrizzly.com>"]

################################################################################

license = "MIT"
documentation = "https://docs.rs/whoami"
homepage = "http://plopgrizzly.com/whoami"
repository = "https://github.com/plopgrizzly/whoami"

################################################################################

readme = "README.md"
description = """
    Whoami is is a library developed by Plop Grizzly for retrieving the current
    user and environment.
"""
keywords = ["user", "username", "whoami", "platform", "detect"]
categories = ["os"]

################################################################################

exclude = ["examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore"]

################################################################################

[dependencies]
libc = "^0.2"
term = { version = "0.4.6", optional = true }

################################################################################

[[bin]]
name = "whoami"
doc = false

################################################################################
